import fs from 'node:fs'
import { compressMessages } from './compress.js'
import { redactMessage } from './secrets.js'
import { estimateMessagesTokens, stringifyContent } from './tokens.js'

export function loadMessagesFile(filePath) {
  const raw = JSON.parse(fs.readFileSync(filePath, 'utf8'))
  const messages = Array.isArray(raw) ? raw : raw.messages
  if (!Array.isArray(messages)) {
    throw new Error('expected an array of messages, or { "messages": [...] }')
  }
  return messages
}

function extractTaskHints(messages) {
  const users = messages.filter((m) => m.role === 'user').map((m) => stringifyContent(m.content).trim())
  const assistants = messages.filter((m) => m.role === 'assistant').map((m) => stringifyContent(m.content).trim())
  const errors = messages
    .map((m) => stringifyContent(m.content))
    .filter((c) => /error|failed|exception|429|timeout/i.test(c))
    .slice(-3)

  return {
    latestUserGoal: users.at(-1)?.slice(0, 500) || '(none)',
    latestAssistant: assistants.at(-1)?.slice(0, 500) || '(none)',
    recentErrors: errors.map((e) => e.slice(0, 240)),
    openQuestions: users.filter((u) => /\?|如何|怎么|why|how/i.test(u)).slice(-3)
  }
}

function roleCounts(messages) {
  const counts = {}
  for (const m of messages) counts[m.role || 'unknown'] = (counts[m.role || 'unknown'] || 0) + 1
  return Object.entries(counts)
    .map(([k, v]) => `${k}:${v}`)
    .join(', ')
}

export function buildHandoffPack(messages, { maxTokens = 1600, sourcePath = '' } = {}) {
  let secretsRedacted = 0
  const redacted = messages.map((m) => {
    const { message, count } = redactMessage(m)
    secretsRedacted += count
    return message
  })

  const tokensBefore = estimateMessagesTokens(redacted)
  const compressed = compressMessages(redacted, { maxTokens })
  const tokensAfter = estimateMessagesTokens(compressed)
  const hints = extractTaskHints(compressed)

  const packet = {
    version: 1,
    generatedAt: new Date().toISOString(),
    sourcePath,
    budget: { maxTokens, tokensBefore, tokensAfter },
    task_state: {
      goal: hints.latestUserGoal,
      last_assistant_summary: hints.latestAssistant,
      blockers: hints.recentErrors,
      open_questions: hints.openQuestions
    },
    next_actions: [
      'Continue from task_state.goal without re-asking known context.',
      'Resolve blockers listed under task_state.blockers first.',
      'If tools are needed, prefer minimal calls and report failures clearly.'
    ],
    plans: {
      A: 'Finish the current goal with the smallest change set.',
      B: 'If blocked, reproduce the latest error with a minimal command, then patch.',
      C: 'If still blocked, ask one clarifying question and propose a fallback path.'
    },
    compressed_messages: compressed
  }

  const markdown = renderMarkdown(packet)
  const ratio =
    tokensBefore === 0 ? '0%' : `${Math.round((1 - tokensAfter / tokensBefore) * 1000) / 10}%`

  return {
    packet,
    markdown,
    stats: {
      messageCount: messages.length,
      tokensBefore,
      tokensAfter,
      compressionRatio: ratio,
      secretsRedacted,
      keptSummary: roleCounts(compressed)
    }
  }
}

function renderMarkdown(packet) {
  const lines = []
  lines.push('# Agent Handoff Packet')
  lines.push('')
  lines.push(`Generated: ${packet.generatedAt}`)
  if (packet.sourcePath) lines.push(`Source: \`${packet.sourcePath}\``)
  lines.push(
    `Budget: ${packet.budget.tokensBefore} → ${packet.budget.tokensAfter} tokens (max ${packet.budget.maxTokens})`
  )
  lines.push('')
  lines.push('## Task State')
  lines.push(`- **Goal:** ${packet.task_state.goal}`)
  lines.push(`- **Last assistant:** ${packet.task_state.last_assistant_summary}`)
  lines.push('- **Blockers:**')
  if (packet.task_state.blockers.length === 0) lines.push('  - (none)')
  else packet.task_state.blockers.forEach((b) => lines.push(`  - ${b}`))
  lines.push('- **Open questions:**')
  if (packet.task_state.open_questions.length === 0) lines.push('  - (none)')
  else packet.task_state.open_questions.forEach((q) => lines.push(`  - ${q}`))
  lines.push('')
  lines.push('## Next Actions')
  packet.next_actions.forEach((a, i) => lines.push(`${i + 1}. ${a}`))
  lines.push('')
  lines.push('## Plans')
  lines.push(`- **A:** ${packet.plans.A}`)
  lines.push(`- **B:** ${packet.plans.B}`)
  lines.push(`- **C:** ${packet.plans.C}`)
  lines.push('')
  lines.push('## Compressed Messages (pasteable JSON)')
  lines.push('```json')
  lines.push(JSON.stringify(packet.compressed_messages, null, 2))
  lines.push('```')
  lines.push('')
  lines.push('_Generated by handoff-pack — local-first, OpenAI-compatible message handoff._')
  lines.push('')
  return lines.join('\n')
}
